// This file was auto-generated by ML.NET Model Builder.
namespace BlazorMLDashboard
{
    public class ModelSettings
    {
        public string RetrainFileName { get; set; }
        public string EvaluationFileName { get; set; }
        public string ModelFileName { get; set; }
        public string PreprocessedTrainDataFileName { get; set; }
        public string AnalysisFileName { get; set; }
        public string PublicPath { get; set; }
        public string PrivatePath { get; set; }
        public char RetrainSeparatorChar { get; set; }
        public bool RetrainHasHeader { get; set; }
        public bool RetrainAllowQuoting { get; set; }

        public string GetPrivatePath(string fileName) => Path.Combine(Environment.CurrentDirectory, PrivatePath, fileName);
        public string GetPublicPath(string fileName) => Path.Combine(Environment.CurrentDirectory, PublicPath, fileName);
    }
    public class MySettings
    {
        public string? Setting1 { get; set; }
        public int Setting2 { get; set; }
    }
}